### ISSUE TITLE
flipper zero

### ISSUE THREAD

**Issue by asiawatcher** [luigicalligaris/dcfake77#2]
Hi there I have a flipper zero and I'm trying to do this implementation

https://lab.flipper.net/apps/dcf77_clock_sync

in the comments it says:

"When using the GPIO, best results are achieved if you connect a ferrite antenna over 330 ohm resistor and a capactior to ground."

any idea what capacitor we use to achive this ? volts capacity ? how will resistor be connected either way is the same ?

I see that for your raspberry implementation that also uses GPIO you dont mention a capacitor is it needed ?

I bought one of these just to use the antenna https://www.ebay.com/itm/203638784817

Thanks

**Comment by luigicalligaris** [comment]
Hello @asiawatcher. I'll be happy to help, just note that this issue is about support for a third-party application and you should have asked them, not me ;)

You can happily ignore the need for a capacitor. The resistor is there to limit the current, and what really does the trick is the inductor.

I think it's best to use an air-wound inductor, that is, a wire with many turns (for cheap wire, I extract the single wires from the twisted pairs of old Ethernet cables or from telephone twisted pairs). What you bought seems to have a component under the epoxy blob and I'm not sure is suitable for your application.

The reason why you use a ferrite when receiving is that ferrite "eats" a lot of the field flowing around it, giving better signal strength. But for transmission I think is not really useful.

**Comment by asiawatcher** [comment]
thanks for your comment i tried messaging them but there was no reply !

This is a very good idea, how many turns and what diameter should it have you reckon ? I mean i can just take a pencil and wrap the wire around it and then remove the pencil or needs something thicker ?

More turns = the best or less the best ? what do you recommend ?

I want to increase range as much as possible i got lots of radio clocks up on the walls and i cant use a ladder every time !! it would be great to sync all of them at the same time or at least from a bigger distance (than 10cm !!)

Thanks for your time i appreciate it

**Comment by luigicalligaris** [comment]
Don't make a small solenoid. You want the watch you are programming to be in near field conditions. Make it larger or of the same order of size w.r.t the watch.

I use a flat coil with a diameter of the size of a fist. More winding = stronger field = better.

If you want to reach all your watches at the same time, it might not be possible, but as a try I would consider putting a large flat coil on the floor under the watches.

**Comment by asiawatcher** [comment]
ok i will try and let you know thanks for everything !

last question if the coil wire is thicker is it better than using thinner wire such as the utp wire ? (in terms of signal strength)

cheers

**Comment by luigicalligaris** [comment]
It makes no difference as long as there less than hundreds of windings, which you won't need, as the total resistance will be dominated by the resistor and the contribution by the windings will be tiny. Just use the cheapest wire you can find.
